<a href="https://colab.research.google.com/github/Hemavathi22-HV/Hemavathi22-HV/blob/main/day-2assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

# Function to perform matrix multiplication
def matrix_multiply(A, B):
    return np.dot(A, B)

# Example matrices
A = np.array([[3, 6],
              [4, 5]])
B = np.array([[5, 6],
              [7, 8]])

# Perform multiplication
result = matrix_multiply(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication Result:\n", result)

Matrix A:
 [[3 6]
 [4 5]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication Result:
 [[57 66]
 [55 64]]


In [10]:
data = [5,10,15,20,25,30]


In [11]:
def min_max_scale(data):
    min_val = min(data)
    max_val = max(data)
    return [(x - min_val) / (max_val - min_val) for x in data]

scaled_data = min_max_scale(data)
print("Original Data:", data)
print("Min-Max Scaled Data:", scaled_data)

Original Data: [5, 10, 15, 20, 25, 30]
Min-Max Scaled Data: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]


In [12]:
def standardize(data):
    mean = sum(data) / len(data)
    std = (sum([(x - mean) ** 2 for x in data]) / len(data)) ** 0.5
    return [(x - mean) / std for x in data]

standardized_data = standardize(data)
print("Standardized Data:", standardized_data)


Standardized Data: [-1.4638501094227996, -0.8783100656536798, -0.2927700218845599, 0.2927700218845599, 0.8783100656536798, 1.4638501094227996]
